### ISSUE TITLE
Error occurred while trying . 

### ISSUE THREAD

**Issue by Boy17000** [LightXEthan/LightAI#1]
evening after setting the API key, and typing in chat while locked in chat mode with a villager it says: An error occurred while trying to reach the OpenAI API. I used the exact same API key that u showed in ur video installation guide.

The log below is from the moment the error started till the moment it was no longer abt the plugin.

The server version is 1.19.3.

**Comment by Boy17000** [comment]
Server console error: [12:43:01 WARN]: java.nio.file.NoSuchFileException: plugins\LightAI\Villager.txt
[12:43:01 WARN]:        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
[12:43:01 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[12:43:01 WARN]:        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[12:43:01 WARN]:        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
[12:43:01 WARN]:        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
[12:43:01 WARN]:        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
[12:43:01 WARN]:        at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
[12:43:01 WARN]:        at LightAI.jar//me.LightXEthan.lightai.Main.loadPrompt(Main.java:109)
[12:43:01 WARN]:        at LightAI.jar//me.LightXEthan.lightai.Main.getDefaultPrompt(Main.java:220)
[12:43:01 WARN]:        at LightAI.jar//me.LightXEthan.lightai.Main.getOpenAiResponse(Main.java:238)
[12:43:01 WARN]:        at LightAI.jar//me.LightXEthan.lightai.Main.onPlayerChat(Main.java:205)
[12:43:01 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor169.execute(Unknown Source)
[12:43:01 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[12:43:01 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[12:43:01 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:43:01 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[12:43:01 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[12:43:01 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[12:43:01 WARN]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:413)
[12:43:01 WARN]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:99)
[12:43:01 WARN]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2391)
[12:43:01 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2547)
[12:43:01 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChat$17(PlayerConnection.java:2228)
[12:43:01 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[12:43:01 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[12:43:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:43:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:43:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:43:01 INFO]: [LightAI] [STDOUT] Prompt not found.
[12:43:01 INFO]: [LightAI] [STDOUT] Player prompt: The following is a conversation between a player and Villager\n\nBoy18000: hi\nVillager:
[12:43:01 INFO]: [LightAI] [STDOUT] Request payload: {"presence_penalty": 0.6,"frequency_penalty": 1.0,  "temperature": 0,60, "stop": ["Boy18000:","Villager:"], "prompt": "The following is a conversation between a player and Villager\n\nBoy18000: hi\nVillager:", "max_tokens": 30, "model": "text-davinci-003"}
[12:43:02 WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.openai.com/v1/completions
[12:43:02 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997)
[12:43:02 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[12:43:02 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[12:43:02 WARN]:        at LightAI.jar//me.LightXEthan.lightai.Main.requestOpenAi(Main.java:303)
[12:43:02 WARN]:        at LightAI.jar//me.LightXEthan.lightai.Main.getOpenAiResponse(Main.java:249)
[12:43:02 WARN]:        at LightAI.jar//me.LightXEthan.lightai.Main.onPlayerChat(Main.java:205)
[12:43:02 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor169.execute(Unknown Source)
[12:43:02 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[12:43:02 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[12:43:02 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:43:02 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[12:43:02 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[12:43:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[12:43:02 WARN]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:413)
[12:43:02 WARN]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:99)
[12:43:02 WARN]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2391)
[12:43:02 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2547)
[12:43:02 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChat$17(PlayerConnection.java:2228)
[12:43:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[12:43:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[12:43:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:43:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:43:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:43:02 INFO]: An error occurred while trying to reach the OpenAI API
> stop

**Comment by Boy17000** [comment]
i used the exact same api key that u showed on ur video installation guide.

**Comment by LightXEthan** [comment]
Hi, Thank you for reporting this error. From the error message, I found there's an issue with the value of the "temperature" key in the request payload.

The 400 in this case generally means the request payload was invalid. Looking further, the key-value `"temperature": 0,60` is not a float value, since there's a comma that should not be there.

I'm very confused where that comma comes from since its hard coded, did you modify the code at all or is from the release page?

**Comment by Boy17000** [comment]
i have not changed any thing from ur code, except opening the api text docu.

Other than that i downloaded the jar from: spigot: 
Version |  Release date
1.0 | Feb 5, 2023

**Comment by polmg8** [comment]
It happens the same to me...
